services:
  # Aplikasi Wagtail (Django)
  wagtail:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - UID=1001  # HARUS SAMA DENGAN USER DI BAWAH
        - GID=1001
    user: "1001:1001"
    ports:
      # - "127.0.0.1:8000:8000"
      - "8000:8000"
    container_name: wagtail
    restart: unless-stopped
    volumes:
      - ./media:/app/media:rw
      - ./static:/app/static:rw
      - ./db.sqlite3:/app/db.sqlite3:rw
    networks:
      - shared_network

networks:
  shared_network:
    external: true