services:
  # Aplikasi Wagtail (Django)
  wagtail:
    user: "1001:1001"
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      # - "127.0.0.1:8000:8000"
      - "8000:8000"
    container_name: wagtail
    restart: unless-stopped
    volumes:
      - ./media:/app/media:rw
      - ./static:/app/static:rw
    networks:
      - shared_network

networks:
  shared_network:
    external: true