services:
  # Aplikasi Wagtail (Django)
  wagtail:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      # - "127.0.0.1:8000:8000"
      - "8000:8000"
    container_name: wagtail
    restart: unless-stopped
    volumes:
      - ./media:/app/media:rw
      - ./static:/app/static:rw
    # environment:
      # Django Settings
      # - DJANGO_SETTINGS_MODULE=core.settings.dev
      # - SECRET_KEY=django-insecure-t+8*b$jp(-^4&mvixpc82wi4k!*7!oo3_q+3nrxk5ab9it+515
      # - DEBUG=1
      # - DATABASE_URL=sqlite:///db/db.sqlite3

    networks:
      - shared_network

networks:
  shared_network:
    external: true