services:
  # Aplikasi Wagtail (Django)
  wagtail:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      # - "127.0.0.1:8000:8000"
      - "8000:8000"
    container_name: wagtail
    restart: unless-stopped
    volumes:
      - ./media:/app/media:rw
      - ./static:/app/static:rw
    environment:
      # Django Settings
      - DJANGO_SETTINGS_MODULE=core.settings.dev  # Ganti dengan modul settings Anda
      - SECRET_KEY=your-ass-key-here  # Ganti dengan secret key kuat!
      - DEBUG=1  # Matikan debug di produksi
      - CSRF_TRUSTED_ORIGINS=https://eveza.id,http://wagtail:8000  # Tambahkan URL internal
      - DATABASE_URL=sqlite:///db/db.sqlite3  # Path ke SQLite di container

    networks:
      - shared_network

networks:
  shared_network:
    external: true