services:
  # Aplikasi Wagtail (Django)
  wagtail:
    build: .
    container_name: wagtail
    restart: unless-stopped
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ./sqlite_data:/app/db  # Simpan data SQLite secara persisten
      - ./static_volume:/app/static  # Volume untuk static files
    environment:
      # Django Settings
      - DJANGO_SETTINGS_MODULE=core.settings.production  # Ganti dengan modul settings Anda
      - SECRET_KEY=your-ass-key-here  # Ganti dengan secret key kuat!
      - DEBUG=0  # Matikan debug di produksi
      - ALLOWED_HOSTS=eveza.id,localhost,127.0.0.1,nginx-proxy,wagtail  # Tambahkan 'wagtail'
      - CSRF_TRUSTED_ORIGINS=https://eveza.id,http://wagtail:8000  # Tambahkan URL internal

      # Database (SQLite)
      - DATABASE_URL=sqlite:///db/db.sqlite3  # Path ke SQLite di container
      
      # Static/Media Files
      - STATIC_ROOT=/app/static
      - MEDIA_ROOT=/app/media  # Opsional, jika menggunakan upload file
      
      # Gunicorn
      - PORT=8000
      - PYTHONUNBUFFERED=1

    networks:
      - shared_network

networks:
  shared_network:
    external: true

volumes:
  sqlite_data:  # Volume untuk SQLite
  static_volume:  # Volume untuk static files