services:
  wagtail:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - UID=1001
        - GID=1001
    user: "1001:1001"
    ports:
      # - "127.0.0.1:8000:8000"
      - "8000:8000"
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_BUCKET_NAME=${MINIO_BUCKET_NAME}
      - MINIO_ENDPOINT=${MINIO_ENDPOINT}
      - MINIO_CUSTOM_DOMAIN=${MINIO_CUSTOM_DOMAIN}
    # depends_on:
    #   postgres:
    #     condition: service_healthy
    # networks:
    #   - shared_network

#   postgres:
#     image: postgres:15-alpine
#     environment:
#       POSTGRES_DB: ${DB_NAME}
#       POSTGRES_USER: ${DB_USER}
#       POSTGRES_PASSWORD: ${DB_PASSWORD}
#     restart: 
#       always
#     ports:
#       - '5432:5432'
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     networks:
#       - shared_network
#     healthcheck:
#       test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
#       interval: 5s
#       timeout: 5s
#       retries: 5

# volumes:
#   postgres_data:

# networks:
#   shared_network:
#     external: true
