# minio-compose.yml

services:
  minio:
    image: quay.io/minio/minio:RELEASE.2023-11-01T01-57-10Z-cpuv1
    ports:
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:9001:9001"
    container_name: minio1
    hostname: minio
    environment:
      - MINIO_ROOT_USER=dicky
      - MINIO_ROOT_PASSWORD=Jul@3225501
      - MINIO_SERVER_URL=https://minio-api.eveza.id
      - MINIO_BROWSER_REDIRECT_URL=https://minio.eveza.id
      - MINIO_API_SECRET_KEY=rahasia1234567890123456789012345
    volumes:
      - ${HOME}/minio/data:/data
      # - ${HOME}/minio/certs:/root/.minio/certs  # Untuk SSL certificates
    command: server /data --console-address ":9001"
    restart: unless-stopped
    networks:
      - shared_network

networks:
  shared_network:
    external: true