# minio-compose.yml

services:
  minio:
    image: quay.io/minio/minio
    container_name: minio1
    hostname: minio
    environment:
      - MINIO_ROOT_USER=dicky
      - MINIO_ROOT_PASSWORD=Jul@3225501
      - MINIO_SERVER_URL=https://minio.eveza.id
      - MINIO_BROWSER_REDIRECT_URL=https://minio.eveza.id
    volumes:
      - ${HOME}/minio/data:/data
      # - ${HOME}/minio/certs:/root/.minio/certs  # Untuk SSL certificates
    command: server /data --console-address ":9001"
    restart: unless-stopped
    networks:
      - shared_network

networks:
  shared_network:
    external: true