# Generated by Django 5.1.7 on 2025-04-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_meta_key', models.CharField(blank=True, null=True)),
                ('index_meta_desc', models.CharField(blank=True, null=True)),
                ('produk_meta_key', models.CharField(blank=True, null=True)),
                ('produk_meta_desc', models.CharField(blank=True, null=True)),
                ('tentang_meta_key', models.CharField(blank=True, null=True)),
                ('tentang_meta_desc', models.CharField(blank=True, null=True)),
                ('kontak_meta_key', models.CharField(blank=True, null=True)),
                ('kontak_meta_desc', models.CharField(blank=True, null=True)),
                ('blog_meta_key', models.CharField(blank=True, null=True)),
                ('blog_meta_desc', models.CharField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
