# Generated by Django 5.1.7 on 2025-04-24 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_setting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alamat', models.CharField(max_length=200)),
                ('telepon', models.CharField(max_length=200)),
                ('whatsapp', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
