# Generated by Django 5.1.7 on 2025-04-24 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_setting', '0002_socialsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialsettings',
            name='alamat',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='socialsettings',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='socialsettings',
            name='telepon',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='socialsettings',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
