# Generated by Django 5.1.7 on 2025-04-24 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('global_setting', '0003_alter_socialsettings_alamat_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SocialSettings',
            new_name='Social',
        ),
    ]
