# Generated by Django 5.1.7 on 2025-04-24 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_setting', '0004_rename_socialsettings_social'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreadCrumb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produk_breadcump', models.ImageField(blank=True, null=True, upload_to='global_setting')),
                ('tentang_breadcump', models.ImageField(blank=True, null=True, upload_to='global_setting')),
                ('kontak_breadcump', models.ImageField(blank=True, null=True, upload_to='global_setting')),
                ('blog_breadcump', models.ImageField(blank=True, null=True, upload_to='global_setting')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
