# Generated by Django 5.1.7 on 2025-04-24 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('global_setting', '0005_breadcrumb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='breadcrumb',
            old_name='blog_breadcump',
            new_name='blog_breadcump_1920x348',
        ),
        migrations.RenameField(
            model_name='breadcrumb',
            old_name='kontak_breadcump',
            new_name='kontak_breadcump_1920x348',
        ),
        migrations.RenameField(
            model_name='breadcrumb',
            old_name='produk_breadcump',
            new_name='produk_breadcump_1920x348',
        ),
        migrations.RenameField(
            model_name='breadcrumb',
            old_name='tentang_breadcump',
            new_name='tentang_breadcump_1920x348',
        ),
    ]
