# Generated by Django 5.1.7 on 2025-05-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "global_setting",
            "0006_rename_blog_breadcump_breadcrumb_blog_breadcump_1920x348_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="FooterText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("footer_text", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
