# Generated by Django 5.1.7 on 2025-05-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("global_setting", "0008_companyprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="social",
            name="embed_map",
            field=models.TextField(blank=True, null=True),
        ),
    ]
