# Generated by Django 5.1.7 on 2025-05-09 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("global_setting", "0009_social_embed_map"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyprofile",
            name="company_logo_138x84",
            field=models.FileField(blank=True, null=True, upload_to="global_setting"),
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="company_logo_69x42",
            field=models.FileField(blank=True, null=True, upload_to="global_setting"),
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="favicon_16x16",
            field=models.FileField(blank=True, null=True, upload_to="global_setting"),
        ),
    ]
