# Generated by Django 5.1.7 on 2025-05-01 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_alter_productcategory_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productcategory",
            old_name="image",
            new_name="image_376x376",
        ),
    ]
