# Generated by Django 5.1.7 on 2025-05-01 18:48

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_product_productimage_productspecification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="product",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="product.product",
            ),
        ),
        migrations.AlterField(
            model_name="productspecification",
            name="product",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="specifications",
                to="product.product",
            ),
        ),
    ]
