# Generated by Django 5.1.7 on 2025-05-07 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0006_product_is_featured_productcategory_is_featured"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productimage",
            old_name="image",
            new_name="image_320x240",
        ),
    ]
