# Generated by Django 5.1.7 on 2025-04-25 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("main_text", models.CharField()),
                ("small_text", models.CharField()),
                (
                    "video_background_555x423",
                    models.ImageField(default="", upload_to="about_us"),
                ),
                ("text_1", models.CharField()),
                ("text_small_1", models.CharField()),
                (
                    "text_icon_35x35_1",
                    models.ImageField(default="", upload_to="about_us"),
                ),
                ("text_2", models.CharField()),
                ("text_small_2", models.CharField()),
                (
                    "text_icon_35x35_2",
                    models.ImageField(default="", upload_to="about_us"),
                ),
                ("text_3", models.CharField()),
                ("text_small_3", models.CharField()),
                (
                    "text_icon_35x35_3",
                    models.ImageField(default="", upload_to="about_us"),
                ),
                ("text_4", models.CharField()),
                ("text_small_4", models.CharField()),
                (
                    "text_icon_35x35_4",
                    models.ImageField(default="", upload_to="about_us"),
                ),
            ],
            options={
                "verbose_name": "About Us",
            },
        ),
    ]
