# Generated by Django 5.1.7 on 2025-04-25 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("about_us", "0002_aboutus_video_url"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aboutus",
            options={},
        ),
    ]
