# Generated by Django 5.1.7 on 2025-04-25 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about_us", "0003_alter_aboutus_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutus",
            name="main_text",
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name="aboutus",
            name="small_text",
            field=models.CharField(null=True),
        ),
    ]
