# Generated by Django 5.1.7 on 2025-04-30 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about_us", "0004_alter_aboutus_main_text_alter_aboutus_small_text"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutus",
            name="site",
            field=models.OneToOneField(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="wagtailcore.site",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="aboutus",
            name="main_text",
            field=models.CharField(default="", null=True),
        ),
        migrations.AlterField(
            model_name="aboutus",
            name="small_text",
            field=models.CharField(default="", null=True),
        ),
        migrations.AlterField(
            model_name="aboutus",
            name="text_1",
            field=models.CharField(default="", null=True),
        ),
        migrations.AlterField(
            model_name="aboutus",
            name="text_2",
            field=models.CharField(default="", null=True),
        ),
        migrations.AlterField(
            model_name="aboutus",
            name="text_3",
            field=models.CharField(default="", null=True),
        ),
        migrations.AlterField(
            model_name="aboutus",
            name="text_4",
            field=models.CharField(default="", null=True),
        ),
        migrations.AlterField(
            model_name="aboutus",
            name="text_small_1",
            field=models.CharField(default="", null=True),
        ),
        migrations.AlterField(
            model_name="aboutus",
            name="text_small_2",
            field=models.CharField(default="", null=True),
        ),
        migrations.AlterField(
            model_name="aboutus",
            name="text_small_3",
            field=models.CharField(default="", null=True),
        ),
        migrations.AlterField(
            model_name="aboutus",
            name="text_small_4",
            field=models.CharField(default="", null=True),
        ),
        migrations.AlterField(
            model_name="aboutus",
            name="video_url",
            field=models.URLField(default="", null=True),
        ),
    ]
