# Generated by Django 5.1.7 on 2025-04-30 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about_us", "0005_aboutus_site_alter_aboutus_main_text_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aboutus",
            name="site",
        ),
        migrations.AlterField(
            model_name="aboutus",
            name="main_text",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="aboutus",
            name="small_text",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="aboutus",
            name="text_1",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="aboutus",
            name="text_2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="aboutus",
            name="text_3",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="aboutus",
            name="text_4",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="aboutus",
            name="text_small_1",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="aboutus",
            name="text_small_2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="aboutus",
            name="text_small_3",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="aboutus",
            name="text_small_4",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="aboutus",
            name="video_url",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
