# Generated by Django 5.1.7 on 2025-04-30 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("about_us", "0006_remove_aboutus_site_alter_aboutus_main_text_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aboutus",
            options={"verbose_name": "About Us Settings"},
        ),
    ]
