# Generated by Django 5.1.7 on 2025-04-30 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about_us", "0007_alter_aboutus_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamSupport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tim_support_190x190",
                    models.ImageField(default="", upload_to="about_us"),
                ),
                (
                    "tim_support_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "tim_support_wa",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "tim_support_link",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
