# Generated by Django 5.1.7 on 2025-04-30 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about_us", "0008_teamsupport"),
    ]

    operations = [
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_image_100x100", models.ImageField(upload_to="testimonials/")),
                ("client_name", models.CharField(max_length=100)),
                ("client_role", models.CharField(max_length=100)),
                ("client_description", models.TextField()),
            ],
            options={
                "verbose_name": "Testimonial",
                "verbose_name_plural": "Testimonials",
            },
        ),
    ]
