# Generated by Django 5.1.7 on 2025-04-30 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about_us", "0009_testimonial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=255)),
                ("answer", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQs",
                "ordering": ["order"],
            },
        ),
        migrations.AlterModelOptions(
            name="teamsupport",
            options={"verbose_name": "Team Support (Max 3)"},
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="client_image_100x100",
            field=models.ImageField(default="", upload_to="about_us"),
        ),
    ]
