# Generated by Django 5.1.7 on 2025-04-30 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("about_us", "0010_faq_alter_teamsupport_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FAQ",
        ),
    ]
