# Generated by Django 5.1.7 on 2025-04-20 08:46

import autoslug.fields
import wagtail.fields
import wagtail.search.index
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogcategory_delete_blogpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategory',
            name='title',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='title')),
                ('image', models.ImageField(upload_to='blog/image')),
                ('content', wagtail.fields.StreamField([('paragraph', 0), ('h4', 1), ('h6', 2), ('ordered_list', 3), ('unordered_list', 4), ('blockquote_1', 5), ('image', 6)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['p', 'a']}), 1: ('wagtail.blocks.CharBlock', (), {'features': ['h4']}), 2: ('wagtail.blocks.CharBlock', (), {'features': ['h6']}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['ol']}), 4: ('wagtail.blocks.RichTextBlock', (), {'features': ['ul']}), 5: ('wagtail.blocks.CharBlock', (), {}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': '800 x 600', 'label': 'Image'})}, null=True)),
                ('meta_key', models.TextField(blank=True, max_length=250, null=True)),
                ('meta_desc', models.TextField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, to='blog.blogcategory')),
            ],
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
    ]
