# Generated by Django 5.1.7 on 2025-04-20 15:22

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blog_is_active_blog_is_feature_alter_blog_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='image',
        ),
        migrations.AddField(
            model_name='blog',
            name='image_1920x640',
            field=models.ImageField(default='', upload_to='media/blog/image'),
        ),
        migrations.AddField(
            model_name='blog',
            name='image_330x220',
            field=models.ImageField(default='', upload_to='media/blog/image'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
