# Generated by Django 5.1.7 on 2025-04-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_blog_image_blog_image_1920x640_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='small_content',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
