# Generated by Django 5.1.7 on 2025-05-01 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_create_homepage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Carousel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("top_text", models.CharField(max_length=255)),
                ("bottom_text", models.CharField(max_length=255)),
                (
                    "image_1200x630",
                    models.ImageField(upload_to="carousel_images/1200x630/"),
                ),
                ("link", models.URLField(blank=True, null=True)),
            ],
        ),
    ]
