# Generated by Django 5.1.7 on 2025-05-01 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_carousel"),
    ]

    operations = [
        migrations.AddField(
            model_name="carousel",
            name="link_text",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
