# Generated by Django 5.1.7 on 2025-05-01 14:00

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_carousel_link_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="OurServices",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", wagtail.fields.RichTextField()),
                (
                    "image_50x50",
                    models.ImageField(upload_to="our_services_images/50x50/"),
                ),
            ],
        ),
    ]
