# Generated by Django 5.1.7 on 2025-05-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_ourservices"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientCarousel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_name", models.CharField(max_length=255)),
                (
                    "image_50x50",
                    models.ImageField(upload_to="client_carousel_images/50x50/"),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="carousel",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="ourservices",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="ourservices",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.DeleteModel(
            name="HomePage",
        ),
    ]
