# Generated by Django 5.1.7 on 2025-05-07 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_clientcarousel_alter_carousel_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CorrugatedBoardThickness",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_600x400",
                    models.ImageField(
                        upload_to="corrugated_board_thickness_images/600x400/"
                    ),
                ),
                ("title", models.CharField(max_length=255)),
            ],
        ),
    ]
